package:
  name: aicspylibczi
  version: 3.0.5

source:
  path: src

test:
  imports:
    - aicspylibczi

requirements:
  run:
    - numpy

build:
  script: |
    source $PYODIDE_ROOT/packages/aicspylibczi/cmake/build_args.sh

about:
  home: https://github.com/AllenCellModeling/aicspylibczi
  PyPI: https://pypi.org/project/aicspylibczi
  summary: A python module and a python extension for Zeiss (CZI/ZISRAW) microscopy files.
  license: GPL-3.0-only
